import * as XLSX from 'xlsx'

export function createPipkinWorkbookData(): Uint8Array {
  const rows = [
    ['PERSONAGEM', 'Pipkin "Sorte Grande"', 'JOGADOR', 'Satsuki'],
    ['CLASSE(S) & NÍVEL(EIS)', 'Clérigo 5', 'RAÇA', 'Folken Limalumes'],
    ['ANTECEDENTE', 'Espião', 'BÔNUS DE PROFICIÊNCIA', '+3'],
    ['FORÇA', '8', 'DESTREZA', '14', 'CONSTITUIÇÃO', '12'],
    ['INTELIGÊNCIA', '10', 'SABEDORIA', '18', 'CARISMA', '14'],
    ['CA', '18', 'PV MÁXIMO', '33', 'VELOCIDADE', '25', 'PERCEPÇÃO PASSIVA', '14'],
    ['PERÍCIAS'],
    ['Acrobacia', '+2'],
    ['Lidar com Animais', '+4'],
    ['Arcana', '+4'],
    ['Atletismo', '-1'],
    ['Enganação', '+5'],
    ['História', '+0'],
    ['Intuição', '+7'],
    ['Intimidação', '+2'],
    ['Investigação', '+0'],
    ['Medicina', '+4'],
    ['Natureza', '+0'],
    ['Percepção', '+4'],
    ['Atuação', '+2'],
    ['Persuasão', '+5'],
    ['Religião', '+0'],
    ['Prestidigitação', '+5'],
    ['Furtividade', '+2'],
    ['Sobrevivência', '+7'],
    ['IDIOMAS E FERRAMENTAS'],
    ['Comum'],
    ['Élfico'],
    ['Pequenino'],
    ['Armas Simples'],
    ['Armaduras Leves, Médias e Escudos'],
    ['CARACTERÍSTICAS DE CLASSE E RAÇA'],
    ['Sorte Incontrolável'],
    ['Mente Genial'],
    ['Agilidade dos Pequeninos'],
    ['Fala Silenciosa'],
    ['Conjuração'],
    ['Ordem Sagrada'],
    ['Ritos Sacros'],
    ['Canalizar Divindade'],
    ['Clérigo do Caos'],
    ['Autoridade Sagrada'],
    ['TALENTOS GERAIS'],
    ['Marca Anômala'],
    ['Raízes profundas'],
    ['TALENTOS DE RAÇA'],
    ['Dedos Leves'],
    ['Escapista'],
    ['TALENTOS EXTRAS'],
    ['MOCHILA & EQUIPAMENTO'],
    ['Scale Mail'],
    ['Shield'],
    ['Potion of Healing'],
    ['Shortbow'],
    ["Explorer's Pack"],
    ['Holy Symbol'],
    ['Agua Benta'],
    ['PO', '1225'],
    ['RESISTÊNCIAS'],
    ['IMUNIDADES'],
    ['VULNERABILIDADES'],
  ]
  const worksheet = XLSX.utils.aoa_to_sheet(rows)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Ficha')
  return new Uint8Array(XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }) as ArrayBuffer)
}
