import * as XLSX from 'xlsx'

export function createPipkinWorkbookData(): Uint8Array {
  const workbook = XLSX.utils.book_new()

  const logRows = createGrid(110, 70)
  setCell(logRows, 5, 2, 'Pipkin "Sorte Grande"')
  setCell(logRows, 4, 30, 'Satsuki')
  setCell(logRows, 4, 19, 'Clérigo 5')
  setCell(logRows, 5, 19, 'CLASSE(S) & NIVEL(EIS)')
  setCell(logRows, 6, 19, 'Folken Limalumes')
  setCell(logRows, 7, 19, 'RACA')
  setCell(logRows, 9, 18, 'ANTECEDENTE')
  setCell(logRows, 10, 2, 'Espião')
  setCell(logRows, 10, 18, 'BONUS DE PROFICIENCIA')
  setCell(logRows, 10, 19, '+3')
  setCell(logRows, 15, 15, 'CA')
  setCell(logRows, 15, 16, '18')
  setCell(logRows, 15, 17, 'PV MAXIMO')
  setCell(logRows, 15, 18, '33')
  setCell(logRows, 15, 19, 'VELOCIDADE')
  setCell(logRows, 15, 20, '25')
  setCell(logRows, 16, 9, 'FORCA')
  setCell(logRows, 16, 8, '-1')
  setCell(logRows, 16, 10, '8')
  setCell(logRows, 17, 9, 'DESTREZA')
  setCell(logRows, 17, 8, '+2')
  setCell(logRows, 17, 10, '14')
  setCell(logRows, 18, 9, 'CONSTITUICAO')
  setCell(logRows, 18, 8, '+1')
  setCell(logRows, 18, 10, '12')
  setCell(logRows, 19, 9, 'INTELIGENCIA')
  setCell(logRows, 19, 8, '+0')
  setCell(logRows, 19, 10, '10')
  setCell(logRows, 20, 9, 'SABEDORIA')
  setCell(logRows, 20, 8, '+4')
  setCell(logRows, 20, 10, '18')
  setCell(logRows, 21, 9, 'CARISMA')
  setCell(logRows, 21, 8, '+2')
  setCell(logRows, 21, 10, '14')
  setCell(logRows, 42, 7, 'PERICIAS')
  setCell(logRows, 43, 7, 'Acrobacia')
  setCell(logRows, 43, 8, '+2')
  setCell(logRows, 44, 7, 'Lidar com Animais')
  setCell(logRows, 44, 8, '+4')
  setCell(logRows, 45, 7, 'Arcana')
  setCell(logRows, 45, 8, '+4')
  setCell(logRows, 46, 7, 'Atletismo')
  setCell(logRows, 46, 8, '-1')
  setCell(logRows, 47, 7, 'Enganacao')
  setCell(logRows, 47, 8, '+5')
  setCell(logRows, 48, 7, 'Historia')
  setCell(logRows, 48, 8, '+0')
  setCell(logRows, 49, 7, 'Intuicao')
  setCell(logRows, 49, 8, '+7')
  setCell(logRows, 50, 7, 'Intimidacao')
  setCell(logRows, 50, 8, '+2')
  setCell(logRows, 51, 7, 'Investigacao')
  setCell(logRows, 51, 8, '+0')
  setCell(logRows, 52, 7, 'Medicina')
  setCell(logRows, 52, 8, '+4')
  setCell(logRows, 53, 7, 'Natureza')
  setCell(logRows, 53, 8, '+0')
  setCell(logRows, 54, 7, 'Percepcao')
  setCell(logRows, 54, 8, '+4')
  setCell(logRows, 55, 7, 'Atuacao')
  setCell(logRows, 55, 8, '+2')
  setCell(logRows, 56, 7, 'Persuasão')
  setCell(logRows, 56, 8, '+5')
  setCell(logRows, 57, 7, 'Religião')
  setCell(logRows, 57, 8, '+0')
  setCell(logRows, 58, 7, 'Prestidigitacao')
  setCell(logRows, 58, 8, '+5')
  setCell(logRows, 59, 7, 'Furtividade')
  setCell(logRows, 59, 8, '+2')
  setCell(logRows, 60, 7, 'Sobrevivencia')
  setCell(logRows, 60, 8, '+7')
  setCell(logRows, 44, 5, 'PERCEPCAO PASSIVA')
  setCell(logRows, 44, 6, '14')
  setCell(logRows, 62, 7, 'IDIOMAS E FERRAMENTAS')
  setCell(logRows, 63, 7, 'Comum')
  setCell(logRows, 64, 7, 'Elfico')
  setCell(logRows, 65, 7, 'Pequenino')
  setCell(logRows, 66, 7, 'Armas Simples')
  setCell(logRows, 67, 7, 'Armaduras Leves, Medias e Escudos')
  setCell(logRows, 42, 17, 'CARACTERISTICAS DE CLASSE E RACA')
  setCell(logRows, 43, 17, 'Sorte Incontrolável')
  setCell(logRows, 44, 17, 'Mente Genial')
  setCell(logRows, 45, 17, 'Agilidade dos Pequeninos')
  setCell(logRows, 46, 17, 'Fala Silenciosa')
  setCell(logRows, 47, 17, 'Conjuração')
  setCell(logRows, 48, 17, 'Ordem Sagrada')
  setCell(logRows, 49, 17, 'Ritos Sacros')
  setCell(logRows, 50, 17, 'Canalizar Divindade')
  setCell(logRows, 51, 17, 'Clérigo do Caos')
  setCell(logRows, 52, 17, 'Autoridade Sagrada')
  setCell(logRows, 53, 17, 'TALENTOS GERAIS')
  setCell(logRows, 54, 17, 'Marca Anômala')
  setCell(logRows, 55, 17, 'Raízes profundas')
  setCell(logRows, 56, 17, 'TALENTOS DE RACA')
  setCell(logRows, 57, 17, 'Dedos Leves')
  setCell(logRows, 58, 17, 'Escapista')
  setCell(logRows, 59, 17, 'TALENTOS EXTRAS')
  setCell(logRows, 84, 15, 'MOCHILA & EQUIPAMENTO')
  setCell(logRows, 85, 15, 'Scale Mail')
  setCell(logRows, 86, 15, 'Shield')
  setCell(logRows, 87, 15, 'Potion of Healing')
  setCell(logRows, 88, 15, 'Shortbow')
  setCell(logRows, 89, 15, "Explorer's Pack")
  setCell(logRows, 90, 15, 'Holy Symbol')
  setCell(logRows, 91, 15, 'Água Benta')
  setCell(logRows, 92, 15, 'PO')
  setCell(logRows, 92, 16, '1225')
  setCell(logRows, 1, 48, 'ITEM')
  setCell(logRows, 1, 49, 'CUSTO')
  setCell(logRows, 1, 50, 'PESO')
  setCell(logRows, 5, 62, 'Artifice')
  setCell(logRows, 60, 56, 'Associated Skills')
  setCell(logRows, 85, 42, 'bludgeoning')
  setCell(logRows, 85, 46, 'piercing')
  setCell(logRows, 85, 47, 'slashing')

  const logWorksheet = XLSX.utils.aoa_to_sheet(logRows)
  logWorksheet['!merges'] = [
    { s: { r: 5, c: 2 }, e: { r: 6, c: 17 } },
    { s: { r: 10, c: 2 }, e: { r: 11, c: 17 } },
  ]
  XLSX.utils.book_append_sheet(workbook, logWorksheet, 'LOG')

  const personagemRows = createGrid(70, 20)
  setCell(personagemRows, 0, 0, 'APARENCIA DO PERSONAGEM')
  setCell(personagemRows, 1, 0, 'TRACOS DE PERSONALIDADE')
  setCell(personagemRows, 2, 0, 'PERSONALIDADE')
  setCell(personagemRows, 42, 1, 'ANTECEDENTE')
  const personagemWorksheet = XLSX.utils.aoa_to_sheet(personagemRows)
  personagemWorksheet['!merges'] = [{ s: { r: 42, c: 1 }, e: { r: 42, c: 8 } }]
  XLSX.utils.book_append_sheet(workbook, personagemWorksheet, 'Personagem')

  return new Uint8Array(XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }) as ArrayBuffer)
}

function createGrid(rowCount: number, colCount: number): string[][] {
  return Array.from({ length: rowCount }, () => Array.from({ length: colCount }, () => ''))
}

function setCell(rows: string[][], row: number, col: number, value: string) {
  rows[row] ??= []
  rows[row][col] = value
}
